<script lang="ts">
	import { selectedProducts, userCountry } from '$lib/utils/stores';
	import { ProgressBar } from '@skeletonlabs/skeleton';
	import LoadingAnim from '$lib/components/general/ui/LoadingAnim.svelte';
	import CompareTable from './compareTable/CompareTable.svelte';

	let tableData: any[]=[];
	let remainingCredit: number = 0;
	let isLoading: boolean = true;

	// ======================= Loading Logic ============================
	import { tweened } from 'svelte/motion';
	let original = 40; // TYPE NUMBER OF SECONDS HERE
	let timer = tweened(original);
	setInterval(() => {
		if ($timer > 0) $timer--;
	}, 1000);
	$: progressValue = ((original - $timer) / original) * 100;

	async function getAIResponse() {
		let response = await fetch('/api/compare', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json'
			},
			body: JSON.stringify({
				selectedProducts: $selectedProducts,
				userCountry: $userCountry
			})
		});

		let data = await response.json();

		tableData = data.tableData;
		remainingCredit = data.finalCredit;
		isLoading = false;

		console.log('Compare.svelte:', data);
	}




	import { onMount } from 'svelte';
	onMount(async () => {
		// getAIResponse();

		tableData = [
    {
        "asin": "B08YYSTK2Z",
        "image": "https://m.media-amazon.com/images/I/614ljJ2q2jL._AC_UL400_.jpg",
        "link": "https://www.amazon.ca/ROCKBROS-Photochromic-Sunglasses-Protection-Transitions/dp/B08YYSTK2Z/ref=sr_1_1?keywords=bicycle+glasses&qid=1684905630&sr=8-1&tag=mapyan-20",
        "rating": 4.1,
        "ratings_total": 174,
        "price_raw": "$34.99",
        "response": {
            "photochromic": "true",
            "polarized": "false",
            "interchangeable lenses": "false",
            "adjustable nose grips": "false",
            "UV protection": "true",
            "good for sports": "true"
        }
    },
    {
        "asin": "B084WS7SN3",
        "image": "https://m.media-amazon.com/images/I/61GQyNjAjsL._AC_UL400_.jpg",
        "link": "https://www.amazon.ca/Queshark-Unbreakable-Sunglasses-Interchangeable-Anti-UV400/dp/B084WS7SN3/ref=sr_1_2?keywords=bicycle+glasses&qid=1684905630&sr=8-2&tag=mapyan-20",
        "rating": 4.3,
        "ratings_total": 5921,
        "price_raw": "$39.99",
        "response": {
            "photochromic": "false",
            "polarized": "true",
            "interchangeable lenses": "true",
            "adjustable nose grips": "false",
            "UV protection": "-",
            "good for sports": "true",
            "good for driving": "true"
        }
    },
    {
        "asin": "B07DGT8K2L",
        "image": "https://m.media-amazon.com/images/I/51iuopeXsiL._AC_UL400_.jpg",
        "link": "https://www.amazon.ca/ROCKBROS-Cycling-Sunglasses-Photochromic-Protection/dp/B07DGT8K2L/ref=sr_1_3?keywords=bicycle+glasses&qid=1684905630&sr=8-3&tag=mapyan-20",
        "rating": 4.3,
        "ratings_total": 1630,
        "price_raw": "$36.99",
        "response": {
            "photochromic": "true",
            "polarized": "false",
            "interchangeable lenses": "false",
            "adjustable nose grips": "true",
            "UV protection": "true",
            "good for sports": "true"
        }
    }
]
isLoading=false;
	});

	
</script>

{#if isLoading}
	<!-- <ProgressRadial width="w-12" stroke={100} /> -->

	<div class="flex flex-col">
		<LoadingAnim />
		<br />
		<ProgressBar
			rounded="rounded-lg"
			class="rounded-none"
			meter="bg-primary-500"
			height="h-4"
			value={progressValue}
		/>

		<br />
		<div class="flex flex-col justify-center items-center text-center">
			<p class="text-2xl">Generating a comparison table</p>
			<br />
			<p>This usually takes about 30 seconds</p>
			<p>We are working to improve the loading speed.</p>
			<p>Thank you for being patient.</p>
		</div>
	</div>
{:else}
	<div class="flex flex-col p-2 h-full w-full">
		<br />

		<div>
			<h2>
				Your Remaining Credit: {remainingCredit}
			</h2>

			<p>*This information has been generated by AI, and has not been confirmed by a human.</p>
		</div>

		<br />
		<hr />
		<br />


	

		<div>
			<CompareTable {tableData} />
		</div>
	</div>
{/if}
