<script lang="ts">
	import { selectedProducts, userCountry } from '$lib/utils/stores';
	import { ProgressRadial } from '@skeletonlabs/skeleton';
    import CompareTable from './compareTable/CompareTable.svelte'
    
    let compareProductsRaw: string = '';
	let remainingCredit: number = 0;
	let isLoading: boolean = true;


	import {onMount} from "svelte";

	onMount(async () => {
	    let response = await fetch(
	        '/api/compare',
	        {
	            method: 'POST',
	            headers: {
	                'Content-Type': 'application/json'
	            },
	            body: JSON.stringify({
	                selectedProducts:$selectedProducts,
	                userCountry:$userCountry
	            })

	    })

	    let data = await response.json()


	    compareProductsRaw = data.response;
	    remainingCredit = data.finalCredit
	    isLoading=false

	    console.log("Compare.svelte:",data)
	});



</script>

{#if isLoading}
	<ProgressRadial width="w-12" stroke={100} />
	<p>This can take up to 2 minutes</p>
{:else}

<div class="flex flex-col p-2">
	<br>

	<div>
		
		<h2>
			Your Remaining Credit: {remainingCredit}
		</h2>

	</div>

	<br>
	<hr>
	<br>

	<p>*Please keep in minds, These results are generated by a machine and have not been confirmed by a human.</p>

	<br>
	
	<div>
		<CompareTable {compareProductsRaw} />

	</div>
</div>

{/if}
